import re
import time
import logging
from typing import Dict, List
from fastapi import Request, HTTPException, status

logger = logging.getLogger("pigeon.security")

# Allowed characters in room codes (canonical 5-character alphabet)
VALID_CODE_PATTERN = re.compile(r"^[A-Za-z0-9]{4,8}$")
# File ID is strictly a 16-hex character token generated by secrets.token_hex(8)
VALID_FILE_ID_PATTERN = re.compile(r"^[0-9a-fA-F]{16}$")

def sanitize_filename(filename: str, max_length: int = 255) -> str:
    """
    Sanitizes client-provided filenames against path traversal, control chars,
    null bytes, and invalid filesystem characters.
    Preserves normal filenames (PDF, PPTX, PNG, JPG, MP4, ZIP, text, etc.).
    """
    if not filename:
        return "unnamed_file"

    # Replace backslashes with slashes, take basename to strip any path traversal
    clean = filename.replace("\\", "/").split("/")[-1].strip()

    # Strip null bytes and non-printable control characters
    clean = "".join(c for c in clean if c.isprintable() and ord(c) not in (0, 127))

    # Strip dangerous shell/filesystem characters but allow safe punctuations
    clean = re.sub(r'[\r\n\t\x00-\x1f\x7f]', '', clean)

    # Strip leading dots or whitespace that could hide files or create relative paths
    clean = clean.lstrip(". ").strip()

    # Disallow reserved names or empty results
    if not clean or clean in (".", "..", "CON", "PRN", "AUX", "NUL"):
        clean = "unnamed_file"

    # Enforce reasonable length limit while preserving file extension
    if len(clean) > max_length:
        parts = clean.rsplit(".", 1)
        if len(parts) == 2:
            ext = "." + parts[1][:10]
            clean = parts[0][: max_length - len(ext)] + ext
        else:
            clean = clean[:max_length]

    return clean

def sanitize_header_filename(filename: str) -> str:
    """
    Sanitizes filename for the Content-Disposition HTTP header.
    Prevents HTTP response header injection (CRLF injection) and quote-breaking.
    """
    clean = filename.replace('"', '').replace('\r', '').replace('\n', '').strip()
    return clean if clean else "download"

def validate_room_code(code: str) -> str:
    """
    Validates room code format. Raises 404 on invalid codes to avoid exposing
    internal regex or system details to potential scanners.
    """
    if not code or not VALID_CODE_PATTERN.match(code.strip()):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Room was not found or has expired."
        )
    return "".join(c for c in code if c.isalnum()).upper()

def validate_file_id(file_id: str) -> str:
    """
    Validates internal file ID format (strictly 16 hex chars).
    Prevents path traversal or arbitrary filesystem probing.
    """
    clean_id = file_id.strip()
    if not VALID_FILE_ID_PATTERN.match(clean_id):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Requested file was not found."
        )
    return clean_id

def get_client_ip(request: Request) -> str:
    """
    Extracts the client IP from request headers (handling X-Forwarded-For reverse proxy)
    or directly from client.host.
    """
    forwarded = request.headers.get("x-forwarded-for")
    if forwarded:
        # First IP in the comma-separated chain is the client
        return forwarded.split(",")[0].strip()
    if request.client and request.client.host:
        return request.client.host
    return "127.0.0.1"

class InMemoryRateLimiter:
    """
    Lightweight, in-memory sliding window rate limiter.
    Requires no external dependencies (Redis/DB). Memory is bounded via periodic pruning.
    """
    def __init__(self):
        # Maps key -> list of timestamp floats
        self._requests: Dict[str, List[float]] = {}

    def is_rate_limited(self, key: str, max_requests: int, window_seconds: int) -> bool:
        now = time.time()
        cutoff = now - window_seconds
        
        timestamps = self._requests.get(key, [])
        # Filter timestamps within current window
        valid_timestamps = [t for t in timestamps if t > cutoff]
        
        if len(valid_timestamps) >= max_requests:
            self._requests[key] = valid_timestamps
            return True
        
        valid_timestamps.append(now)
        self._requests[key] = valid_timestamps
        return False

    def prune(self, max_age_seconds: int = 120):
        """Prunes stale rate-limit buckets to prevent memory accumulation."""
        now = time.time()
        cutoff = now - max_age_seconds
        keys_to_delete = []
        for key, timestamps in list(self._requests.items()):
            active = [t for t in timestamps if t > cutoff]
            if active:
                self._requests[key] = active
            else:
                keys_to_delete.append(key)
        for k in keys_to_delete:
            self._requests.pop(k, None)

# Global rate limiters
# Limit room creations to 15 per minute per IP to prevent storage exhaustion
upload_rate_limiter = InMemoryRateLimiter()
# Limit failed code lookups to 25 per minute per IP to mitigate brute-force code guessing
code_guess_rate_limiter = InMemoryRateLimiter()

